### ISSUE TITLE
#F01-02 : Mettre les première maquettes Figma

### ISSUE THREAD

**Issue by SylvainCostes** [GreenTreep/Frontend#2]
L'objectif ici serait de créer une URL Figma permettant la collaboration en temps réel, afin de conceptualiser et visualiser le design potentiel du front-end de l'application

**Comment by SylvainCostes** [comment]
Je mettrais en commentaire le lien quand j'aurais la foi de créer le figma

**Comment by ArezkiBazizi** [comment]
Le figma collaborative est créée, on commencera bientôt les maquettes..
